"""
migrations/0001_initial.py
--------------------------
Migración inicial generada automáticamente por Django el 2026-02-04.

Registra en el historial de migraciones los modelos originales del
sistema, todos con managed=False, lo que significa que Django NO
crea ni modifica estas tablas — solo las conoce para poder hacer
consultas ORM sobre ellas.

Las tablas registradas en esta migración son:
    Autoevaluacion, Cargo, Competencia, Departamento, Dimension,
    EvaluacionJefatura, NivelJerarquico, ResultadoConsolidado,
    TextosEvaluacion, Trabajador.

Nota: esta migración no ejecuta ningún DDL en la base de datos.
Las tablas físicas son creadas por el comando crear_tablas o
por el script creacion_tablas.sql ejecutado manualmente en pgAdmin.
Esta migración existe únicamente para que Django tenga registro
del estado inicial del esquema y pueda rastrear los cambios
posteriores correctamente.
"""
# Generated by Django 5.2.6 on 2026-02-04 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autoevaluacion',
            fields=[
                ('id_autoevaluacion', models.AutoField(primary_key=True, serialize=False)),
                ('puntaje', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha_evaluacion', models.DateField()),
                ('momento_evaluacion', models.DateTimeField()),
                ('estado_finalizacion', models.BooleanField(default=False)),
                ('comentario', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'autoevaluacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id_cargo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_cargo', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'cargo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('id_competencia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_competencia', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'competencia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id_departamento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_departamento', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'departamento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dimension',
            fields=[
                ('id_dimension', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_dimension', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'dimension',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EvaluacionJefatura',
            fields=[
                ('id_evaluacion_jefatura', models.AutoField(primary_key=True, serialize=False)),
                ('puntaje', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha_evaluacion', models.DateField()),
                ('momento_evaluacion', models.DateTimeField()),
                ('estado_finalizacion', models.BooleanField(default=False)),
                ('comentario', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'evaluacion_jefatura',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NivelJerarquico',
            fields=[
                ('id_nivel_jerarquico', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_nivel_jerarquico', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'nivel_jerarquico',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ResultadoConsolidado',
            fields=[
                ('id_resultado', models.AutoField(primary_key=True, serialize=False)),
                ('puntaje_autoev', models.DecimalField(decimal_places=2, max_digits=5)),
                ('puntaje_jefe', models.DecimalField(decimal_places=2, max_digits=5)),
                ('diferencia', models.DecimalField(decimal_places=2, max_digits=5)),
                ('periodo', models.IntegerField()),
                ('fecha_consolidacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'resultado_consolidado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TextosEvaluacion',
            fields=[
                ('id_textos_evaluacion', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_excel', models.CharField(max_length=10, unique=True)),
                ('texto', models.TextField()),
            ],
            options={
                'db_table': 'textos_evaluacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id_trabajador', models.AutoField(primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=40)),
                ('apellido_paterno', models.CharField(max_length=40)),
                ('apellido_materno', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=80)),
                ('genero', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'trabajador',
                'managed': False,
            },
        ),
    ]
