"""
migrations/0002_alter_autoevaluacion_table_alter_cargo_table_and_more.py
------------------------------------------------------------------------
Migración generada el 2026-02-10. Renombra los nombres de tabla de
todos los modelos originales de minúsculas a mayúsculas, alineando
el ORM de Django con la convención de nombres reales en PostgreSQL.

No ejecuta DDL en la base de datos (todos los modelos son
managed=False). Solo actualiza el metadato db_table de cada modelo
en el historial de migraciones.

Cambios aplicados:
    autoevaluacion       → AUTOEVALUACION
    cargo                → CARGO
    competencia          → COMPETENCIA
    departamento         → DEPARTAMENTO
    dimension            → DIMENSION
    evaluacionjefatura   → EVALUACION_JEFATURA
    niveljerarquico      → NIVEL_JERARQUICO
    resultadoconsolidado → RESULTADO_CONSOLIDADO
    textosevaluacion     → TEXTOS_EVALUACION
    trabajador           → TRABAJADOR
"""
# Generated by Django 5.2.6 on 2026-02-10 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuestionario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='autoevaluacion',
            table='AUTOEVALUACION',
        ),
        migrations.AlterModelTable(
            name='cargo',
            table='CARGO',
        ),
        migrations.AlterModelTable(
            name='competencia',
            table='COMPETENCIA',
        ),
        migrations.AlterModelTable(
            name='departamento',
            table='DEPARTAMENTO',
        ),
        migrations.AlterModelTable(
            name='dimension',
            table='DIMENSION',
        ),
        migrations.AlterModelTable(
            name='evaluacionjefatura',
            table='EVALUACION_JEFATURA',
        ),
        migrations.AlterModelTable(
            name='niveljerarquico',
            table='NIVEL_JERARQUICO',
        ),
        migrations.AlterModelTable(
            name='resultadoconsolidado',
            table='RESULTADO_CONSOLIDADO',
        ),
        migrations.AlterModelTable(
            name='textosevaluacion',
            table='TEXTOS_EVALUACION',
        ),
        migrations.AlterModelTable(
            name='trabajador',
            table='TRABAJADOR',
        ),
    ]
