"""
migrations/0003_escala.py
-------------------------
Migración generada el 2026-02-11. Registra el modelo Escala en el
historial de migraciones de Django.

El modelo tiene managed=False, por lo que no crea la tabla física
en la base de datos — solo permite al ORM hacer consultas sobre
la tabla ESCALA existente.

Campos registrados en esta migración:
    id_escala   → IntegerField (PK)
    descripcion → CharField(100)

Nota: el modelo Escala fue evolucionando en migraciones posteriores
para agregar los campos valor y titulo que tiene actualmente.
"""
# Generated by Django 5.2.6 on 2026-02-11 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuestionario', '0002_alter_autoevaluacion_table_alter_cargo_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Escala',
            fields=[
                ('id_escala', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'ESCALA',
                'managed': False,
            },
        ),
    ]
