"""
migrations/0004_descripcionrespuesta.py
---------------------------------------
Migración generada el 2026-02-16. Registra el modelo
DescripcionRespuesta en el historial de migraciones de Django.

El modelo tiene managed=False. La tabla DESCRIPCION_RESPUESTA
fue un modelo intermedio usado para describir las opciones de
respuesta del cuestionario antes de que esta funcionalidad
fuera absorbida por el modelo Escala.

Campos registrados:
    id_descripcion_respuesta → AutoField (PK)
    titulo                   → CharField(100)
    descripcion              → TextField

Nota: este modelo fue eliminado posteriormente en la migración
0010, cuando se consolidó la lógica de descripciones en Escala.
"""
# Generated by Django 5.2.6 on 2026-02-16 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuestionario', '0003_escala'),
    ]

    operations = [
        migrations.CreateModel(
            name='DescripcionRespuesta',
            fields=[
                ('id_descripcion_respuesta', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
            options={
                'db_table': 'DESCRIPCION_RESPUESTA',
                'managed': False,
            },
        ),
    ]
