"""
migrations/0005_promptgemini.py
--------------------------------
Migración generada el 2026-02-20. Crea el modelo PromptGemini
en la base de datos.

A diferencia de las migraciones anteriores, este modelo NO tiene
managed=False, por lo que Django crea y gestiona la tabla
PROMPT_GEMINI directamente.

Campos creados:
    id_prompt        → AutoField (PK)
    prompt_texto     → TextField
    timestamp        → DateTimeField (auto_now_add, ordenamiento por defecto)
    respuesta_gemini → TextField (nullable)
    pdf_generado     → BooleanField (default False)

Nota: en migraciones posteriores se agregaron los campos
archivo_pdf, reporte_global_id y empresa a este modelo.
"""
# Generated by Django 5.2.6 on 2026-02-20 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuestionario', '0004_descripcionrespuesta'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptGemini',
            fields=[
                ('id_prompt', models.AutoField(primary_key=True, serialize=False)),
                ('prompt_texto', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('respuesta_gemini', models.TextField(blank=True, null=True)),
                ('pdf_generado', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'PROMPT_GEMINI',
                'ordering': ['-timestamp'],
            },
        ),
    ]
