"""
migrations/0007_alter_reporteglobal_periodo.py
----------------------------------------------
Migración generada el 2026-02-24. Ajuste menor al modelo ReporteGlobal.

Cambio aplicado:
    periodo → agrega default=2026, evitando que el campo sea
              obligatorio al crear un ReporteGlobal sin especificar
              período explícitamente.
"""
# Generated by Django 5.2.6 on 2026-02-24 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuestionario', '0006_reporteglobal_promptgemini_archivo_pdf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporteglobal',
            name='periodo',
            field=models.IntegerField(default=2026),
        ),
    ]
