"""
migrations/0008_biblioteca.py
------------------------------
Migración generada el 2026-02-26. Registra el modelo Biblioteca
en el historial de migraciones de Django.

El modelo tiene managed=False, por lo que no crea la tabla física
— solo permite al ORM hacer consultas sobre la tabla BIBLIOTECA
existente.

Campos registrados:
    id_biblioteca → AutoField (PK)
    nombre        → CharField(100)
    archivo       → BinaryField (editable=True, almacena PDFs)
    estado_carga  → BooleanField (default False)
    fecha_carga   → DateTimeField (auto_now_add)

Nota: en migraciones posteriores se agregó la FK a Empresa
para asociar cada documento a una empresa específica.
"""
# Generated by Django 5.2.6 on 2026-02-26 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuestionario', '0007_alter_reporteglobal_periodo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biblioteca',
            fields=[
                ('id_biblioteca', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('archivo', models.BinaryField(editable=True)),
                ('estado_carga', models.BooleanField(default=False)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'BIBLIOTECA',
                'managed': False,
            },
        ),
    ]
