"""
migrations/0009_codigoevaluacion_empresa.py
-------------------------------------------
Migración generada el 2026-03-05. Registra los modelos
CodigoEvaluacion y Empresa en el historial de migraciones.

Ambos modelos tienen managed=False, por lo que no crean tablas
físicas — solo permiten al ORM hacer consultas sobre las tablas
CODIGO_EVALUACION y EMPRESA existentes.

Campos registrados:

CodigoEvaluacion:
    id_codigo_evaluacion             → AutoField (PK)
    textos_evaluacion_codigo_excel   → CharField(10)

Empresa:
    id_empresa     → AutoField (PK)
    nombre_empresa → CharField(100)
    rut_empresa    → CharField(20, unique)
    empresa_activa → BooleanField (default False)
    registrada_en  → DateTimeField (auto_now_add)
"""
# Generated by Django 5.2.6 on 2026-03-05 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuestionario', '0008_biblioteca'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoEvaluacion',
            fields=[
                ('id_codigo_evaluacion', models.AutoField(primary_key=True, serialize=False)),
                ('textos_evaluacion_codigo_excel', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'CODIGO_EVALUACION',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id_empresa', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_empresa', models.CharField(max_length=100)),
                ('rut_empresa', models.CharField(max_length=20, unique=True)),
                ('empresa_activa', models.BooleanField(default=False)),
                ('registrada_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'EMPRESA',
                'managed': False,
            },
        ),
    ]
