"""
migrations/0010_delete_descripcionrespuesta_promptgemini_empresa_and_more.py
----------------------------------------------------------------------------
Migración generada el 2026-03-13. Limpieza de modelo obsoleto y
vinculación de modelos existentes con Empresa.

Cambios aplicados:

DescripcionRespuesta → eliminado del historial de migraciones.
    Su funcionalidad fue absorbida por el modelo Escala.

PromptGemini — campo agregado:
    empresa → ForeignKey a Empresa (nullable, ON DELETE SET NULL),
              permite filtrar prompts y sus informes por empresa.

ReporteGlobal — campo agregado:
    empresa → ForeignKey a Empresa (nullable, ON DELETE SET NULL),
              asocia cada reporte global a la empresa que lo generó.
"""
# Generated by Django 5.2.6 on 2026-03-13 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuestionario', '0009_codigoevaluacion_empresa'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DescripcionRespuesta',
        ),
        migrations.AddField(
            model_name='promptgemini',
            name='empresa',
            field=models.ForeignKey(blank=True, db_column='EMPRESA_ID_EMPRESA', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cuestionario.empresa'),
        ),
        migrations.AddField(
            model_name='reporteglobal',
            name='empresa',
            field=models.ForeignKey(blank=True, db_column='EMPRESA_ID_EMPRESA', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cuestionario.empresa'),
        ),
    ]
