"""
migrations/0011_ratpreguntas_ratrespuestas_registroversiones_and_more.py
------------------------------------------------------------------------
Migración generada el 2026-05-07. Introduce el módulo RAT con tres
nuevos modelos gestionados por Django (managed=True).

Modelos creados:

RATPreguntas (tabla RAT_PREGUNTAS):
    Registra las actividades de tratamiento de datos de una empresa.
    Campos: actividad_tratamiento, categorias_datos,
    descripcion_titulares, finalidad_tratamiento, base_legitimidad
    (choices: consentimiento/contrato/obligacion_legal/interes_legitimo),
    periodo_conservacion, fuente_datos.
    FKs: empresa, responsable (Trabajador), version (RegistroVersiones,
    nullable ON DELETE SET NULL).

RATRespuestas (tabla RAT_RESPUESTAS):
    Respuestas de los trabajadores a las preguntas RAT.
    Campos: respuesta (TextField), created_at, updated_at.
    FKs: pregunta (RATPreguntas, CASCADE), trabajador.

RegistroVersiones (tabla REGISTRO_VERSIONES):
    Historial de versiones del RAT de una empresa.
    Campos: version, fecha_modificacion (auto_now_add), 
    motivo_modificacion.
    FK: empresa.

Nota: en esta versión RATPreguntas apuntaba directamente a Empresa.
En la migración 0013 esta FK fue reemplazada por InstrumentoEmpresa.
"""
# Generated by Django 5.2.6 on 2026-05-07 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuestionario', '0010_delete_descripcionrespuesta_promptgemini_empresa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RATPreguntas',
            fields=[
                ('id_rat_pregunta', models.AutoField(primary_key=True, serialize=False)),
                ('actividad_tratamiento', models.CharField(max_length=255)),
                ('categorias_datos', models.TextField()),
                ('descripcion_titulares', models.TextField()),
                ('finalidad_tratamiento', models.TextField()),
                ('base_legitimidad', models.CharField(choices=[('consentimiento', 'Consentimiento'), ('contrato', 'Contrato'), ('obligacion_legal', 'Obligación legal'), ('interes_legitimo', 'Interés legítimo')], max_length=50)),
                ('periodo_conservacion', models.PositiveIntegerField()),
                ('fuente_datos', models.CharField(max_length=255)),
                ('empresa', models.ForeignKey(db_column='empresa_id_empresa', on_delete=django.db.models.deletion.DO_NOTHING, to='cuestionario.empresa')),
                ('responsable', models.ForeignKey(db_column='trabajador_id_responsable', on_delete=django.db.models.deletion.DO_NOTHING, related_name='preguntas_rat_responsable', to='cuestionario.trabajador')),
            ],
            options={
                'db_table': 'RAT_PREGUNTAS',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RATRespuestas',
            fields=[
                ('id_rat_respuesta', models.AutoField(primary_key=True, serialize=False)),
                ('respuesta', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pregunta', models.ForeignKey(db_column='rat_preguntas_id_rat_pregunta', on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='cuestionario.ratpreguntas')),
                ('trabajador', models.ForeignKey(db_column='trabajador_id_trabajador', on_delete=django.db.models.deletion.DO_NOTHING, to='cuestionario.trabajador')),
            ],
            options={
                'db_table': 'RAT_RESPUESTAS',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RegistroVersiones',
            fields=[
                ('id_registro_version', models.AutoField(primary_key=True, serialize=False)),
                ('version', models.CharField(max_length=20)),
                ('fecha_modificacion', models.DateField(auto_now_add=True)),
                ('motivo_modificacion', models.TextField()),
                ('empresa', models.ForeignKey(db_column='empresa_id_empresa', on_delete=django.db.models.deletion.DO_NOTHING, to='cuestionario.empresa')),
            ],
            options={
                'db_table': 'REGISTRO_VERSIONES',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='ratpreguntas',
            name='version',
            field=models.ForeignKey(blank=True, db_column='registro_versiones_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cuestionario.registroversiones'),
        ),
    ]
