"""
migrations/0012_instrumento_remove_ratpreguntas_empresa_and_more.py
-------------------------------------------------------------------
Migración generada el 2026-05-21. Introduce el catálogo global de
instrumentos y la tabla pivote empresa-instrumento.

Cambios aplicados:

Instrumento (tabla INSTRUMENTO, managed=True):
    Catálogo global de instrumentos RAT disponibles.
    Campos: id_instrumento, nombre_instrumento (unique),
    descripcion (nullable), activo (default True).
    Poblado inicial vía RunSQL con: 'RAT 1', 'RAT 2', 'EvalDesempeño'.

InstrumentoEmpresa (tabla INSTRUMENTO_EMPRESA, managed=True):
    Tabla pivote que relaciona empresas con instrumentos.
    Campos: id_instrumento_empresa, habilitado (default True),
    fecha_habilitacion (auto_now_add).
    FKs: empresa, instrumento.
    Restricción unique_together: (instrumento, empresa) — una empresa
    no puede tener el mismo instrumento asignado dos veces.

RATPreguntas — cambio de FK:
    Se elimina el campo empresa y se agrega instrumento
    (FK a Instrumento, default=1 para filas existentes).
    Esto desacopla las preguntas RAT de la empresa y las vincula
    al catálogo global de instrumentos.

Nota: en la migración 0013 la FK instrumento de RATPreguntas
fue reemplazada por instrumento_empresa (FK a InstrumentoEmpresa)
para mayor granularidad por empresa.
"""
# Generated by Django 5.2.6 on 2026-05-21 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuestionario', '0011_ratpreguntas_ratrespuestas_registroversiones_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrumento',
            fields=[
                ('id_instrumento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_instrumento', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'INSTRUMENTO',
                'managed': True,
            },
        ),
        migrations.RunSQL(
            "INSERT INTO \"INSTRUMENTO\" (nombre_instrumento, activo) VALUES ('RAT 1', true), ('RAT 2', true), ('EvalDesempeño', true);",
            reverse_sql="DELETE FROM \"INSTRUMENTO\" WHERE nombre_instrumento IN ('RAT 1', 'RAT 2', 'EvalDesempeño');"
        ),
        migrations.RemoveField(
            model_name='ratpreguntas',
            name='empresa',
        ),
        migrations.AddField(
            model_name='ratpreguntas',
            name='instrumento',
            field=models.ForeignKey(db_column='instrumento_id', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='cuestionario.instrumento'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='InstrumentoEmpresa',
            fields=[
                ('id_instrumento_empresa', models.AutoField(primary_key=True, serialize=False)),
                ('habilitado', models.BooleanField(default=True)),
                ('fecha_habilitacion', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(db_column='empresa_id_empresa', on_delete=django.db.models.deletion.DO_NOTHING, to='cuestionario.empresa')),
                ('instrumento', models.ForeignKey(db_column='instrumento_id', on_delete=django.db.models.deletion.DO_NOTHING, to='cuestionario.instrumento')),
            ],
            options={
                'db_table': 'INSTRUMENTO_EMPRESA',
                'managed': True,
                'unique_together': {('instrumento', 'empresa')},
            },
        ),
    ]
