# Generated by Django 5.2.6 on 2026-05-26 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuestionario', '0013_ratpreguntas_instrumento_empresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='RATPlantillaPregunta',
            fields=[
                ('id_plantilla', models.AutoField(primary_key=True, serialize=False)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('enunciado', models.TextField()),
                ('tipo', models.CharField(choices=[('texto', 'Texto libre'), ('sino', 'Sí / No'), ('escala', 'Escala 1-5')], default='texto', max_length=10)),
                ('instrumento', models.ForeignKey(db_column='instrumento_id', on_delete=django.db.models.deletion.CASCADE, related_name='plantilla_preguntas', to='cuestionario.instrumento')),
            ],
            options={
                'db_table': 'RAT_PLANTILLA_PREGUNTA',
                'ordering': ['orden'],
                'managed': True,
            },
        ),
    ]
