"""
migrations/0014_ratplantillapregunta.py
----------------------------------------
Migración generada el 2026-05-26. Crea el modelo RATPlantillaPregunta
para definir la estructura de preguntas base de un instrumento RAT.

RATPlantillaPregunta (tabla RAT_PLANTILLA_PREGUNTA, managed=True):
    Define las preguntas plantilla asociadas a un Instrumento global,
    independiente de cualquier empresa. Sirve como estructura base
    que puede clonarse al asignar un instrumento a una empresa.

    Campos:
        id_plantilla → AutoField (PK)
        orden        → PositiveSmallIntegerField (default 0),
                       determina el orden de aparición de las preguntas.
        enunciado    → TextField, texto de la pregunta.
        tipo         → CharField con choices:
                           'texto'  → Texto libre
                           'sino'   → Sí / No
                           'escala' → Escala 1-5
    FK:
        instrumento  → Instrumento (CASCADE), related_name='plantilla_preguntas'.

    Ordenamiento por defecto: ['orden'].

Nota: este modelo es el catálogo global de preguntas por instrumento.
Las preguntas activas por empresa se gestionan en RATPreguntas,
vinculadas a InstrumentoEmpresa.
"""
# Generated by Django 5.2.6 on 2026-05-26 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuestionario', '0013_ratpreguntas_instrumento_empresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='RATPlantillaPregunta',
            fields=[
                ('id_plantilla', models.AutoField(primary_key=True, serialize=False)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('enunciado', models.TextField()),
                ('tipo', models.CharField(choices=[('texto', 'Texto libre'), ('sino', 'Sí / No'), ('escala', 'Escala 1-5')], default='texto', max_length=10)),
                ('instrumento', models.ForeignKey(db_column='instrumento_id', on_delete=django.db.models.deletion.CASCADE, related_name='plantilla_preguntas', to='cuestionario.instrumento')),
            ],
            options={
                'db_table': 'RAT_PLANTILLA_PREGUNTA',
                'ordering': ['orden'],
                'managed': True,
            },
        ),
    ]
