# Generated by Django 5.2.6 on 2026-05-28 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuestionario', '0014_ratplantillapregunta'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumento',
            name='tipo',
            field=models.CharField(choices=[('rat', 'Registro de Actividad de Tratamiento (RAT)'), ('evaluacion', 'Evaluación de Desempeño')], default='rat', max_length=20),
        ),
    ]
