# Generated by Django 5.2.6 on 2026-05-28 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuestionario', '0015_instrumento_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratpreguntas',
            name='tipo',
            field=models.CharField(choices=[('texto', 'Texto libre'), ('sino', 'Sí / No'), ('escala', 'Escala 1-5')], default='texto', max_length=10),
        ),
    ]
