# Generated by Django 5.2.6 on 2026-06-10 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuestionario', '0017_rename_kickoff_to_rat1'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratpreguntas',
            name='destinatarios',
            field=models.ForeignKey(blank=True, db_column='trabajador_id_destinatario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='preguntas_rat_destinatario', to='cuestionario.trabajador'),
        ),
    ]
