# Generated by Django 5.2.6 on 2026-06-10 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuestionario', '0018_ratpreguntas_destinatarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratpreguntas',
            name='categorias_datos',
            field=models.CharField(choices=[('contactabilidad', 'Datos de contactabilidad de personas'), ('bancarios', 'Datos bancarios o finanzas personales'), ('historia_clinica', 'Datos de historia clínica de personas')], max_length=50),
        ),
    ]
