# Generated by Django 5.2.6 on 2026-06-11 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuestionario', '0019_alter_ratpreguntas_categorias_datos'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratpreguntas',
            name='periodo_unidad',
            field=models.CharField(choices=[('dias', 'Días'), ('meses', 'Meses'), ('anos', 'Años')], default='meses', max_length=10),
        ),
        migrations.AlterField(
            model_name='ratpreguntas',
            name='base_legitimidad',
            field=models.CharField(max_length=200),
        ),
    ]
