# Generated by Django 5.2.6 on 2026-06-12 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuestionario', '0020_ratpreguntas_periodo_unidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratpreguntas',
            name='base_legitimidad',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='ratpreguntas',
            name='descripcion_titulares',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='ratpreguntas',
            name='finalidad_tratamiento',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='ratpreguntas',
            name='fuente_datos',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='ratpreguntas',
            name='periodo_conservacion',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ratpreguntas',
            name='tipo',
            field=models.CharField(choices=[('texto', 'Texto libre'), ('sino', 'Sí / No'), ('escala', 'Escala 1-5'), ('select_categorias', 'Selector de categorías')], default='texto', max_length=20),
        ),
    ]
