# Generated by Django 5.2.6 on 2026-06-12 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuestionario', '0021_alter_ratpreguntas_base_legitimidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratpreguntas',
            name='tipo',
            field=models.CharField(choices=[('texto', 'Texto libre'), ('sino', 'Sí / No'), ('escala', 'Escala 1-5'), ('select_categorias', 'Selector de categorías'), ('periodo', 'Período (número + unidad)')], default='texto', max_length=20),
        ),
    ]
