# Generated by Django 5.2.6 on 2026-06-12 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuestionario', '0022_alter_ratpreguntas_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratpreguntas',
            name='tipo',
            field=models.CharField(choices=[('texto', 'Texto libre'), ('sino', 'Sí / No'), ('escala', 'Escala 1-5'), ('select_categorias', 'Selector de categorías'), ('periodo', 'Período (número + unidad)'), ('listado_usuarios', 'Listado de usuarios')], default='texto', max_length=20),
        ),
    ]
