# Generated by Django 5.2.6 on 2026-06-23 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuestionario', '0023_alter_ratpreguntas_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratpreguntas',
            name='tipo',
            field=models.CharField(choices=[('texto', 'Texto libre'), ('sino', 'Sí / No'), ('escala', 'Escala 1-5'), ('select_categorias', 'Selector de categorías'), ('periodo', 'Período (número + unidad)'), ('listado_usuarios', 'Listado de usuarios'), ('select_actividad', 'Selector de actividad de tratamiento'), ('select_formato', 'Selector de formato de archivo'), ('select_base_legitimidad', 'Selector de base de legitimidad (múltiple)')], default='texto', max_length=30),
        ),
    ]
