# Generated by Django 5.2.6 on 2026-06-23 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuestionario', '0024_alter_ratpreguntas_tipo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ratpreguntas',
            options={'managed': True, 'ordering': ['orden', 'id_rat_pregunta']},
        ),
        migrations.AddField(
            model_name='ratpreguntas',
            name='orden',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
