-- =========================
-- creacion_tablas.sql
-- =========================
-- Script DDL para crear las tablas del sistema en PostgreSQL.
-- Debe ejecutarse sobre la BD SistemaRAT_BD DESPUÉS de correr
-- python manage.py migrate (para que auth_user ya exista).
--
-- Tablas creadas (en orden de dependencias):
--   EMPRESA → BIBLIOTECA, REPORTE_GLOBAL, PROMPT_GEMINI,
--   DEPARTAMENTO, NIVEL_JERARQUICO, ESCALA, DIMENSION,
--   COMPETENCIA, CARGO, TEXTOS_EVALUACION, CODIGO_EVALUACION,
--   TRABAJADOR, AUTOEVALUACION, EVALUACION_JEFATURA,
--   RESULTADO_CONSOLIDADO.
--
-- Notas importantes:
--   - Las tablas INSTRUMENTO, INSTRUMENTO_EMPRESA, RAT_PREGUNTAS,
--     RAT_RESPUESTAS, REGISTRO_VERSIONES y RAT_PLANTILLA_PREGUNTA
--     son managed=True y las crea Django con migrate.
--   - TRABAJADOR tiene FK a auth_user(id) ON DELETE SET NULL,
--     por eso migrate debe correr primero.
--   - RESULTADO_CONSOLIDADO tiene EVALUACION_JEFATURA nullable
--     para trabajadores sin jefe directo.
--   - TEXTOS_EVALUACION y CODIGO_EVALUACION usan FK compuesta
--     (codigo_excel, empresa_id) como referencia.
--   - session_replication_role = 'replica' deshabilita la
--     verificación de FK durante la creación para evitar
--     errores de orden. Requiere permisos de superusuario
--     (no disponible en Render free tier — usar el script
--     sin esas líneas en ese caso).
-- =========================

-- =========================
-- Script de creación de tablas para PostgreSQL
-- Compatible con Django + SistemaRAT
-- Ejecutar en psql o pgAdmin sobre la BD: SistemaRAT_BD
-- =========================

-- Deshabilitar verificación de FK temporalmente
SET session_replication_role = 'replica';

-- =========================
-- Tabla Empresa
-- =========================
CREATE TABLE "EMPRESA" (
    "ID_EMPRESA"      SERIAL PRIMARY KEY,
    "NOMBRE_EMPRESA"  VARCHAR(100) NOT NULL,
    "RUT_EMPRESA"     VARCHAR(20)  NOT NULL UNIQUE,
    "EMPRESA_ACTIVA"  BOOLEAN      NOT NULL DEFAULT FALSE,
    "REGISTRADA_EN"   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- =========================
-- Biblioteca
-- =========================
CREATE TABLE "BIBLIOTECA" (
    "ID_BIBLIOTECA"     SERIAL PRIMARY KEY,
    "NOMBRE"            VARCHAR(100) NOT NULL,
    "ARCHIVO"           BYTEA        NOT NULL,
    "ESTADO_CARGA"      BOOLEAN      NOT NULL DEFAULT FALSE,
    "FECHA_CARGA"       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "EMPRESA_ID_EMPRESA" INT         NULL,

    CONSTRAINT "BIBLIOTECA_EMPRESA_FK"
        FOREIGN KEY ("EMPRESA_ID_EMPRESA") REFERENCES "EMPRESA"("ID_EMPRESA")
);

-- =========================
-- Reporte Global
-- =========================
CREATE TABLE "REPORTE_GLOBAL" (
    "ID_REPORTE_GLOBAL"  SERIAL PRIMARY KEY,
    "CONTENIDO_PDF"      BYTEA     NOT NULL,
    "TIMESTAMP"          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "TOTAL_TRABAJADORES" INT       NOT NULL DEFAULT 0,
    "PERIODO"            INT       NOT NULL DEFAULT 2026,
    "EMPRESA_ID_EMPRESA" INT       NULL,

    CONSTRAINT "REPORTE_GLOBAL_EMPRESA_FK"
        FOREIGN KEY ("EMPRESA_ID_EMPRESA") REFERENCES "EMPRESA"("ID_EMPRESA")
);

-- =========================
-- Prompt Gemini
-- =========================
CREATE TABLE "PROMPT_GEMINI" (
    "ID_PROMPT"          SERIAL PRIMARY KEY,
    "PROMPT_TEXTO"       TEXT      NOT NULL,
    "TIMESTAMP"          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "RESPUESTA_GEMINI"   TEXT      NULL,
    "PDF_GENERADO"       BOOLEAN   NOT NULL DEFAULT FALSE,
    "ARCHIVO_PDF"        BYTEA     NULL,
    "REPORTE_GLOBAL_ID"  INT       NULL,
    "EMPRESA_ID_EMPRESA" INT       NULL,

    CONSTRAINT "FK_PROMPT_REPORTE"
        FOREIGN KEY ("REPORTE_GLOBAL_ID") REFERENCES "REPORTE_GLOBAL"("ID_REPORTE_GLOBAL") ON DELETE SET NULL,

    CONSTRAINT "PROMPT_GEMINI_EMPRESA_FK"
        FOREIGN KEY ("EMPRESA_ID_EMPRESA") REFERENCES "EMPRESA"("ID_EMPRESA")
);

-- =========================
-- Tabla Departamento
-- =========================
CREATE TABLE "DEPARTAMENTO" (
    "ID_DEPARTAMENTO"    SERIAL PRIMARY KEY,
    "NOMBRE_DEPARTAMENTO" VARCHAR(50) NOT NULL,
    "EMPRESA_ID_EMPRESA" INT         NOT NULL,

    CONSTRAINT "DEPARTAMENTO_EMPRESA_FK"
        FOREIGN KEY ("EMPRESA_ID_EMPRESA") REFERENCES "EMPRESA"("ID_EMPRESA")
);

-- =========================
-- Tabla Nivel Jerarquico
-- =========================
CREATE TABLE "NIVEL_JERARQUICO" (
    "ID_NIVEL_JERARQUICO"     SERIAL PRIMARY KEY,
    "NOMBRE_NIVEL_JERARQUICO" VARCHAR(50) NOT NULL,
    "EMPRESA_ID_EMPRESA"      INT         NOT NULL,

    CONSTRAINT "NIVEL_JERARQUICO_EMPRESA_FK"
        FOREIGN KEY ("EMPRESA_ID_EMPRESA") REFERENCES "EMPRESA"("ID_EMPRESA")
);

-- =========================
-- Tabla Escala
-- =========================
CREATE TABLE "ESCALA" (
    "ID_ESCALA"          SERIAL PRIMARY KEY,
    "VALOR"              INT          NOT NULL,
    "TITULO"             VARCHAR(100) NOT NULL,
    "DESCRIPCION"        VARCHAR(250) NOT NULL,
    "EMPRESA_ID_EMPRESA" INT          NOT NULL,

    CONSTRAINT "ESCALA_EMPRESA_FK"
        FOREIGN KEY ("EMPRESA_ID_EMPRESA") REFERENCES "EMPRESA"("ID_EMPRESA")
);

-- =========================
-- Tabla Dimension
-- =========================
CREATE TABLE "DIMENSION" (
    "ID_DIMENSION"       SERIAL PRIMARY KEY,
    "NOMBRE_DIMENSION"   VARCHAR(50) NOT NULL,
    "EMPRESA_ID_EMPRESA" INT         NOT NULL,

    CONSTRAINT "DIMENSION_EMPRESA_FK"
        FOREIGN KEY ("EMPRESA_ID_EMPRESA") REFERENCES "EMPRESA"("ID_EMPRESA")
);

-- =========================
-- Tabla Competencia
-- =========================
CREATE TABLE "COMPETENCIA" (
    "ID_COMPETENCIA"          SERIAL PRIMARY KEY,
    "NOMBRE_COMPETENCIA"      VARCHAR(50) NOT NULL,
    "DIMENSION_ID_DIMENSION"  INT         NOT NULL,
    "EMPRESA_ID_EMPRESA"      INT         NOT NULL,

    CONSTRAINT "COMPETENCIA_DIMENSION_FK"
        FOREIGN KEY ("DIMENSION_ID_DIMENSION") REFERENCES "DIMENSION"("ID_DIMENSION"),

    CONSTRAINT "COMPETENCIA_EMPRESA_FK"
        FOREIGN KEY ("EMPRESA_ID_EMPRESA") REFERENCES "EMPRESA"("ID_EMPRESA")
);

-- =========================
-- Tabla Cargo
-- =========================
CREATE TABLE "CARGO" (
    "ID_CARGO"                              SERIAL PRIMARY KEY,
    "NOMBRE_CARGO"                          VARCHAR(50) NOT NULL,
    "EMPRESA_ID_EMPRESA"                    INT         NOT NULL,
    "NIVEL_JERARQUICO_ID_NIVEL_JERARQUICO"  INT         NOT NULL,

    CONSTRAINT "CARGO_NIVEL_JERARQUICO_FK"
        FOREIGN KEY ("NIVEL_JERARQUICO_ID_NIVEL_JERARQUICO") REFERENCES "NIVEL_JERARQUICO"("ID_NIVEL_JERARQUICO"),

    CONSTRAINT "CARGO_EMPRESA_FK"
        FOREIGN KEY ("EMPRESA_ID_EMPRESA") REFERENCES "EMPRESA"("ID_EMPRESA")
);

-- =========================
-- Tabla Textos Evaluación
-- =========================
CREATE TABLE "TEXTOS_EVALUACION" (
    "ID_TEXTOS_EVALUACION"                  SERIAL PRIMARY KEY,
    "CODIGO_EXCEL"                          VARCHAR(10) NOT NULL,
    "TEXTO"                                 TEXT        NOT NULL,
    "EMPRESA_ID_EMPRESA"                    INT         NOT NULL,
    "DIMENSION_ID_DIMENSION"                INT         NOT NULL,
    "COMPETENCIA_ID_COMPETENCIA"            INT         NOT NULL,
    "NIVEL_JERARQUICO_ID_NIVEL_JERARQUICO"  INT         NOT NULL,

    UNIQUE ("CODIGO_EXCEL", "EMPRESA_ID_EMPRESA"),

    CONSTRAINT "TEXTOS_EVALUACION_EMPRESA_FK"
        FOREIGN KEY ("EMPRESA_ID_EMPRESA") REFERENCES "EMPRESA"("ID_EMPRESA"),

    CONSTRAINT "TEXTOS_EVALUACION_DIMENSION_FK"
        FOREIGN KEY ("DIMENSION_ID_DIMENSION") REFERENCES "DIMENSION"("ID_DIMENSION"),

    CONSTRAINT "TEXTOS_EVALUACION_COMPETENCIA_FK"
        FOREIGN KEY ("COMPETENCIA_ID_COMPETENCIA") REFERENCES "COMPETENCIA"("ID_COMPETENCIA"),

    CONSTRAINT "TEXTOS_EVALUACION_NIVEL_FK"
        FOREIGN KEY ("NIVEL_JERARQUICO_ID_NIVEL_JERARQUICO") REFERENCES "NIVEL_JERARQUICO"("ID_NIVEL_JERARQUICO")
);

-- =========================
-- Tabla Código Evaluación
-- =========================
CREATE TABLE "CODIGO_EVALUACION" (
    "ID_CODIGO_EVALUACION"                  SERIAL PRIMARY KEY,
    "EMPRESA_ID_EMPRESA"                    INT         NOT NULL,
    "DIMENSION_ID_DIMENSION"                INT         NOT NULL,
    "COMPETENCIA_ID_COMPETENCIA"            INT         NOT NULL,
    "NIVEL_JERARQUICO_ID_NIVEL_JERARQUICO"  INT         NOT NULL,
    "TEXTOS_EVALUACION_CODIGO_EXCEL"        VARCHAR(10) NOT NULL,
    "TEXTOS_EVALUACION_EMPRESA_ID_EMPRESA"  INT         NOT NULL,

    CONSTRAINT "CODIGO_EVALUACION_UC1"
        UNIQUE ("EMPRESA_ID_EMPRESA", "TEXTOS_EVALUACION_CODIGO_EXCEL"),

    CONSTRAINT "CODIGO_EVALUACION_EMPRESA_FK"
        FOREIGN KEY ("EMPRESA_ID_EMPRESA") REFERENCES "EMPRESA"("ID_EMPRESA"),

    CONSTRAINT "CODIGO_EVALUACION_DIMENSION_FK"
        FOREIGN KEY ("DIMENSION_ID_DIMENSION") REFERENCES "DIMENSION"("ID_DIMENSION"),

    CONSTRAINT "CODIGO_EVALUACION_COMPETENCIA_FK"
        FOREIGN KEY ("COMPETENCIA_ID_COMPETENCIA") REFERENCES "COMPETENCIA"("ID_COMPETENCIA"),

    CONSTRAINT "CODIGO_EVALUACION_NIVEL_FK"
        FOREIGN KEY ("NIVEL_JERARQUICO_ID_NIVEL_JERARQUICO") REFERENCES "NIVEL_JERARQUICO"("ID_NIVEL_JERARQUICO"),

    CONSTRAINT "CODIGO_EVALUACION_TEXTOS_FK"
        FOREIGN KEY ("TEXTOS_EVALUACION_CODIGO_EXCEL", "TEXTOS_EVALUACION_EMPRESA_ID_EMPRESA")
        REFERENCES "TEXTOS_EVALUACION"("CODIGO_EXCEL", "EMPRESA_ID_EMPRESA")
);

-- =========================
-- Tabla Trabajador (Vinculada con Django Auth)
-- Nota: auth_user debe existir previamente (creada por Django migrations)
-- =========================
CREATE TABLE "TRABAJADOR" (
    "ID_TRABAJADOR"                         SERIAL PRIMARY KEY,
    "RUT"                                   VARCHAR(20) NOT NULL UNIQUE,
    "ID_JEFE_DIRECTO"                       INT         NULL,
    "NOMBRE"                                VARCHAR(40) NOT NULL,
    "APELLIDO_PATERNO"                      VARCHAR(40) NOT NULL,
    "APELLIDO_MATERNO"                      VARCHAR(40) NOT NULL,
    "EMAIL"                                 VARCHAR(80) NOT NULL,
    "GENERO"                                VARCHAR(10) NOT NULL,
    "ES_COORDINADOR"                        BOOLEAN     NOT NULL DEFAULT FALSE,
    "EMPRESA_ID_EMPRESA"                    INT         NOT NULL,
    "NIVEL_JERARQUICO_ID_NIVEL_JERARQUICO"  INT         NOT NULL,
    "CARGO_ID_CARGO"                        INT         NOT NULL,
    "DEPARTAMENTO_ID_DEPARTAMENTO"          INT         NOT NULL,
    "USER_ID"                               INT         UNIQUE NULL,

    CONSTRAINT "TRABAJADOR_EMPRESA_FK"
        FOREIGN KEY ("EMPRESA_ID_EMPRESA") REFERENCES "EMPRESA"("ID_EMPRESA"),

    CONSTRAINT "TRABAJADOR_NIVEL_JERARQUICO_FK"
        FOREIGN KEY ("NIVEL_JERARQUICO_ID_NIVEL_JERARQUICO") REFERENCES "NIVEL_JERARQUICO"("ID_NIVEL_JERARQUICO"),

    CONSTRAINT "TRABAJADOR_CARGO_FK"
        FOREIGN KEY ("CARGO_ID_CARGO") REFERENCES "CARGO"("ID_CARGO"),

    CONSTRAINT "TRABAJADOR_DEPARTAMENTO_FK"
        FOREIGN KEY ("DEPARTAMENTO_ID_DEPARTAMENTO") REFERENCES "DEPARTAMENTO"("ID_DEPARTAMENTO"),

    CONSTRAINT "TRABAJADOR_JEFE_FK"
        FOREIGN KEY ("ID_JEFE_DIRECTO") REFERENCES "TRABAJADOR"("ID_TRABAJADOR"),

    CONSTRAINT "TRABAJADOR_USER_FK"
        FOREIGN KEY ("USER_ID") REFERENCES auth_user(id) ON DELETE SET NULL
);

-- =========================
-- Tabla Autoevaluación
-- =========================
CREATE TABLE "AUTOEVALUACION" (
    "ID_AUTOEVALUACION"                     SERIAL PRIMARY KEY,
    "PUNTAJE"                               INT     NOT NULL,
    "FECHA_EVALUACION"                      DATE    NOT NULL,
    "MOMENTO_EVALUACION"                    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "ESTADO_FINALIZACION"                   BOOLEAN NOT NULL DEFAULT FALSE,
    "COMENTARIO"                            TEXT    NULL,
    "TRABAJADOR_ID_TRABAJADOR"              INT     NOT NULL,
    "TEXTOS_EVALUACION_CODIGO_EXCEL"        VARCHAR(10) NOT NULL,
    "TEXTOS_EVALUACION_EMPRESA_ID_EMPRESA"  INT     NOT NULL,
    "ESCALA_ID_ESCALA"                      INT     NOT NULL,

    CONSTRAINT "AUTOEVALUACION_TRABAJADOR_FK"
        FOREIGN KEY ("TRABAJADOR_ID_TRABAJADOR") REFERENCES "TRABAJADOR"("ID_TRABAJADOR"),

    CONSTRAINT "AUTOEVALUACION_TEXTOS_EVALUACION_FK"
        FOREIGN KEY ("TEXTOS_EVALUACION_CODIGO_EXCEL", "TEXTOS_EVALUACION_EMPRESA_ID_EMPRESA")
        REFERENCES "TEXTOS_EVALUACION"("CODIGO_EXCEL", "EMPRESA_ID_EMPRESA"),

    CONSTRAINT "AUTOEVALUACION_ESCALA_FK"
        FOREIGN KEY ("ESCALA_ID_ESCALA") REFERENCES "ESCALA"("ID_ESCALA")
);

-- =========================
-- Tabla Evaluación Jefatura
-- =========================
CREATE TABLE "EVALUACION_JEFATURA" (
    "ID_EVALUACION_JEFATURA"                SERIAL PRIMARY KEY,
    "PUNTAJE"                               INT     NOT NULL,
    "EVALUADOR_ID_TRABAJADOR"               INT     NOT NULL,
    "FECHA_EVALUACION"                      DATE    NOT NULL,
    "MOMENTO_EVALUACION"                    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "ESTADO_FINALIZACION"                   BOOLEAN NOT NULL DEFAULT FALSE,
    "COMENTARIO"                            TEXT    NULL,
    "TRABAJADOR_ID_TRABAJADOR"              INT     NOT NULL,
    "TEXTOS_EVALUACION_CODIGO_EXCEL"        VARCHAR(10) NOT NULL,
    "TEXTOS_EVALUACION_EMPRESA_ID_EMPRESA"  INT     NOT NULL,
    "ESCALA_ID_ESCALA"                      INT     NOT NULL,

    CONSTRAINT "EVALUACION_JEFATURA_TRABAJADOR_FK"
        FOREIGN KEY ("TRABAJADOR_ID_TRABAJADOR") REFERENCES "TRABAJADOR"("ID_TRABAJADOR"),

    CONSTRAINT "EVALUACION_JEFATURA_EVALUADOR_FK"
        FOREIGN KEY ("EVALUADOR_ID_TRABAJADOR") REFERENCES "TRABAJADOR"("ID_TRABAJADOR"),

    CONSTRAINT "EVALUACION_JEFATURA_TEXTOS_EVALUACION_FK"
        FOREIGN KEY ("TEXTOS_EVALUACION_CODIGO_EXCEL", "TEXTOS_EVALUACION_EMPRESA_ID_EMPRESA")
        REFERENCES "TEXTOS_EVALUACION"("CODIGO_EXCEL", "EMPRESA_ID_EMPRESA"),

    CONSTRAINT "EVALUACION_JEFATURA_ESCALA_FK"
        FOREIGN KEY ("ESCALA_ID_ESCALA") REFERENCES "ESCALA"("ID_ESCALA")
);

-- =========================
-- Tabla Resultado Consolidado
-- =========================
CREATE TABLE "RESULTADO_CONSOLIDADO" (
    "ID_RESULTADO_CONSOLIDADO"                  SERIAL PRIMARY KEY,
    "PUNTAJE_AUTOEV"                            INT NOT NULL,
    "PUNTAJE_JEFE"                              INT NOT NULL,
    "DIFERENCIA"                                INT NOT NULL,
    "PERIODO"                                   INT NOT NULL,
    "TRABAJADOR_ID_TRABAJADOR"                  INT NOT NULL,
    "AUTOEVALUACION_ID_AUTOEVALUACION"          INT NOT NULL,
    "EVALUACION_JEFATURA_ID_EVALUACION_JEFATURA" INT NULL,
    "TEXTOS_EVALUACION_CODIGO_EXCEL"            VARCHAR(10) NOT NULL,
    "TEXTOS_EVALUACION_EMPRESA_ID_EMPRESA"      INT         NOT NULL,

    CONSTRAINT "TRABAJADOR_CODIGO_PERIODO"
        UNIQUE ("TRABAJADOR_ID_TRABAJADOR", "TEXTOS_EVALUACION_CODIGO_EXCEL", "PERIODO"),

    CONSTRAINT "RESULTADO_CONSOLIDADO_TRABAJADOR_FK"
        FOREIGN KEY ("TRABAJADOR_ID_TRABAJADOR") REFERENCES "TRABAJADOR"("ID_TRABAJADOR"),

    CONSTRAINT "RESULTADO_CONSOLIDADO_AUTOEVALUACION_FK"
        FOREIGN KEY ("AUTOEVALUACION_ID_AUTOEVALUACION") REFERENCES "AUTOEVALUACION"("ID_AUTOEVALUACION"),

    CONSTRAINT "RESULTADO_CONSOLIDADO_EVALUACION_JEFATURA_FK"
        FOREIGN KEY ("EVALUACION_JEFATURA_ID_EVALUACION_JEFATURA") REFERENCES "EVALUACION_JEFATURA"("ID_EVALUACION_JEFATURA"),

    CONSTRAINT "RESULTADO_CONSOLIDADO_TEXTOS_EVALUACION_FK"
        FOREIGN KEY ("TEXTOS_EVALUACION_CODIGO_EXCEL", "TEXTOS_EVALUACION_EMPRESA_ID_EMPRESA")
        REFERENCES "TEXTOS_EVALUACION"("CODIGO_EXCEL", "EMPRESA_ID_EMPRESA")
);

-- Rehabilitar verificación de FK
SET session_replication_role = 'origin';