from django.core.management.base import BaseCommand
from django.db import connection

SQL = """
CREATE TABLE IF NOT EXISTS "EMPRESA" (
    "ID_EMPRESA" SERIAL PRIMARY KEY,
    "NOMBRE_EMPRESA" VARCHAR(100) NOT NULL,
    "RUT_EMPRESA" VARCHAR(20) NOT NULL UNIQUE,
    "EMPRESA_ACTIVA" BOOLEAN NOT NULL DEFAULT FALSE,
    "REGISTRADA_EN" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "BIBLIOTECA" (
    "ID_BIBLIOTECA" SERIAL PRIMARY KEY,
    "NOMBRE" VARCHAR(100) NOT NULL,
    "ARCHIVO" BYTEA NOT NULL,
    "ESTADO_CARGA" BOOLEAN NOT NULL DEFAULT FALSE,
    "FECHA_CARGA" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "EMPRESA_ID_EMPRESA" INT NULL REFERENCES "EMPRESA"("ID_EMPRESA")
);

CREATE TABLE IF NOT EXISTS "REPORTE_GLOBAL" (
    "ID_REPORTE_GLOBAL" SERIAL PRIMARY KEY,
    "CONTENIDO_PDF" BYTEA NOT NULL,
    "TIMESTAMP" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "TOTAL_TRABAJADORES" INT NOT NULL DEFAULT 0,
    "PERIODO" INT NOT NULL DEFAULT 2026,
    "EMPRESA_ID_EMPRESA" INT NULL REFERENCES "EMPRESA"("ID_EMPRESA")
);

CREATE TABLE IF NOT EXISTS "PROMPT_GEMINI" (
    "ID_PROMPT" SERIAL PRIMARY KEY,
    "PROMPT_TEXTO" TEXT NOT NULL,
    "TIMESTAMP" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "RESPUESTA_GEMINI" TEXT NULL,
    "PDF_GENERADO" SMALLINT NOT NULL DEFAULT 0,
    "ARCHIVO_PDF" BYTEA NULL,
    "REPORTE_GLOBAL_ID" INT NULL REFERENCES "REPORTE_GLOBAL"("ID_REPORTE_GLOBAL") ON DELETE SET NULL,
    "EMPRESA_ID_EMPRESA" INT NULL REFERENCES "EMPRESA"("ID_EMPRESA")
);

CREATE TABLE IF NOT EXISTS "DEPARTAMENTO" (
    "ID_DEPARTAMENTO" SERIAL PRIMARY KEY,
    "NOMBRE_DEPARTAMENTO" VARCHAR(50) NOT NULL,
    "EMPRESA_ID_EMPRESA" INT NOT NULL REFERENCES "EMPRESA"("ID_EMPRESA")
);

CREATE TABLE IF NOT EXISTS "NIVEL_JERARQUICO" (
    "ID_NIVEL_JERARQUICO" SERIAL PRIMARY KEY,
    "NOMBRE_NIVEL_JERARQUICO" VARCHAR(50) NOT NULL,
    "EMPRESA_ID_EMPRESA" INT NOT NULL REFERENCES "EMPRESA"("ID_EMPRESA")
);

CREATE TABLE IF NOT EXISTS "ESCALA" (
    "ID_ESCALA" SERIAL PRIMARY KEY,
    "VALOR" INT NOT NULL,
    "TITULO" VARCHAR(100) NOT NULL,
    "DESCRIPCION" VARCHAR(250) NOT NULL,
    "EMPRESA_ID_EMPRESA" INT NOT NULL REFERENCES "EMPRESA"("ID_EMPRESA")
);

CREATE TABLE IF NOT EXISTS "DIMENSION" (
    "ID_DIMENSION" SERIAL PRIMARY KEY,
    "NOMBRE_DIMENSION" VARCHAR(50) NOT NULL,
    "EMPRESA_ID_EMPRESA" INT NOT NULL REFERENCES "EMPRESA"("ID_EMPRESA")
);

CREATE TABLE IF NOT EXISTS "COMPETENCIA" (
    "ID_COMPETENCIA" SERIAL PRIMARY KEY,
    "NOMBRE_COMPETENCIA" VARCHAR(50) NOT NULL,
    "DIMENSION_ID_DIMENSION" INT NOT NULL REFERENCES "DIMENSION"("ID_DIMENSION"),
    "EMPRESA_ID_EMPRESA" INT NOT NULL REFERENCES "EMPRESA"("ID_EMPRESA")
);

CREATE TABLE IF NOT EXISTS "CARGO" (
    "ID_CARGO" SERIAL PRIMARY KEY,
    "NOMBRE_CARGO" VARCHAR(50) NOT NULL,
    "EMPRESA_ID_EMPRESA" INT NOT NULL REFERENCES "EMPRESA"("ID_EMPRESA"),
    "NIVEL_JERARQUICO_ID_NIVEL_JERARQUICO" INT NOT NULL REFERENCES "NIVEL_JERARQUICO"("ID_NIVEL_JERARQUICO")
);

CREATE TABLE IF NOT EXISTS "TEXTOS_EVALUACION" (
    "ID_TEXTOS_EVALUACION" SERIAL PRIMARY KEY,
    "CODIGO_EXCEL" VARCHAR(10) NOT NULL,
    "TEXTO" TEXT NOT NULL,
    "EMPRESA_ID_EMPRESA" INT NOT NULL REFERENCES "EMPRESA"("ID_EMPRESA"),
    "DIMENSION_ID_DIMENSION" INT NOT NULL REFERENCES "DIMENSION"("ID_DIMENSION"),
    "COMPETENCIA_ID_COMPETENCIA" INT NOT NULL REFERENCES "COMPETENCIA"("ID_COMPETENCIA"),
    "NIVEL_JERARQUICO_ID_NIVEL_JERARQUICO" INT NOT NULL REFERENCES "NIVEL_JERARQUICO"("ID_NIVEL_JERARQUICO"),
    UNIQUE ("CODIGO_EXCEL", "EMPRESA_ID_EMPRESA")
);

CREATE TABLE IF NOT EXISTS "CODIGO_EVALUACION" (
    "ID_CODIGO_EVALUACION" SERIAL PRIMARY KEY,
    "EMPRESA_ID_EMPRESA" INT NOT NULL REFERENCES "EMPRESA"("ID_EMPRESA"),
    "DIMENSION_ID_DIMENSION" INT NOT NULL REFERENCES "DIMENSION"("ID_DIMENSION"),
    "COMPETENCIA_ID_COMPETENCIA" INT NOT NULL REFERENCES "COMPETENCIA"("ID_COMPETENCIA"),
    "NIVEL_JERARQUICO_ID_NIVEL_JERARQUICO" INT NOT NULL REFERENCES "NIVEL_JERARQUICO"("ID_NIVEL_JERARQUICO"),
    "TEXTOS_EVALUACION_CODIGO_EXCEL" VARCHAR(10) NOT NULL,
    "TEXTOS_EVALUACION_EMPRESA_ID_EMPRESA" INT NOT NULL,
    UNIQUE ("EMPRESA_ID_EMPRESA", "TEXTOS_EVALUACION_CODIGO_EXCEL"),
    FOREIGN KEY ("TEXTOS_EVALUACION_CODIGO_EXCEL", "TEXTOS_EVALUACION_EMPRESA_ID_EMPRESA")
        REFERENCES "TEXTOS_EVALUACION"("CODIGO_EXCEL", "EMPRESA_ID_EMPRESA")
);

CREATE TABLE IF NOT EXISTS "TRABAJADOR" (
    "ID_TRABAJADOR" SERIAL PRIMARY KEY,
    "RUT" VARCHAR(20) NOT NULL UNIQUE,
    "ID_JEFE_DIRECTO" INT NULL REFERENCES "TRABAJADOR"("ID_TRABAJADOR"),
    "NOMBRE" VARCHAR(40) NOT NULL,
    "APELLIDO_PATERNO" VARCHAR(40) NOT NULL,
    "APELLIDO_MATERNO" VARCHAR(40) NOT NULL,
    "EMAIL" VARCHAR(80) NOT NULL,
    "GENERO" VARCHAR(10) NOT NULL,
    "ES_COORDINADOR" BOOLEAN NOT NULL,
    "EMPRESA_ID_EMPRESA" INT NOT NULL REFERENCES "EMPRESA"("ID_EMPRESA"),
    "NIVEL_JERARQUICO_ID_NIVEL_JERARQUICO" INT NOT NULL REFERENCES "NIVEL_JERARQUICO"("ID_NIVEL_JERARQUICO"),
    "CARGO_ID_CARGO" INT NOT NULL REFERENCES "CARGO"("ID_CARGO"),
    "DEPARTAMENTO_ID_DEPARTAMENTO" INT NOT NULL REFERENCES "DEPARTAMENTO"("ID_DEPARTAMENTO"),
    "USER_ID" INT UNIQUE NULL REFERENCES auth_user(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS "AUTOEVALUACION" (
    "ID_AUTOEVALUACION" SERIAL PRIMARY KEY,
    "PUNTAJE" INT NOT NULL,
    "FECHA_EVALUACION" DATE NOT NULL,
    "MOMENTO_EVALUACION" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "ESTADO_FINALIZACION" BOOLEAN NOT NULL DEFAULT FALSE,
    "COMENTARIO" TEXT NULL,
    "TRABAJADOR_ID_TRABAJADOR" INT NOT NULL REFERENCES "TRABAJADOR"("ID_TRABAJADOR"),
    "TEXTOS_EVALUACION_CODIGO_EXCEL" VARCHAR(10) NOT NULL,
    "TEXTOS_EVALUACION_EMPRESA_ID_EMPRESA" INT NOT NULL,
    "ESCALA_ID_ESCALA" INT NOT NULL REFERENCES "ESCALA"("ID_ESCALA"),
    FOREIGN KEY ("TEXTOS_EVALUACION_CODIGO_EXCEL", "TEXTOS_EVALUACION_EMPRESA_ID_EMPRESA")
        REFERENCES "TEXTOS_EVALUACION"("CODIGO_EXCEL", "EMPRESA_ID_EMPRESA")
);

CREATE TABLE IF NOT EXISTS "EVALUACION_JEFATURA" (
    "ID_EVALUACION_JEFATURA" SERIAL PRIMARY KEY,
    "PUNTAJE" INT NOT NULL,
    "EVALUADOR_ID_TRABAJADOR" INT NOT NULL REFERENCES "TRABAJADOR"("ID_TRABAJADOR"),
    "FECHA_EVALUACION" DATE NOT NULL,
    "MOMENTO_EVALUACION" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "ESTADO_FINALIZACION" BOOLEAN NOT NULL DEFAULT FALSE,
    "COMENTARIO" TEXT NULL,
    "TRABAJADOR_ID_TRABAJADOR" INT NOT NULL REFERENCES "TRABAJADOR"("ID_TRABAJADOR"),
    "TEXTOS_EVALUACION_CODIGO_EXCEL" VARCHAR(10) NOT NULL,
    "TEXTOS_EVALUACION_EMPRESA_ID_EMPRESA" INT NOT NULL,
    "ESCALA_ID_ESCALA" INT NOT NULL REFERENCES "ESCALA"("ID_ESCALA"),
    FOREIGN KEY ("TEXTOS_EVALUACION_CODIGO_EXCEL", "TEXTOS_EVALUACION_EMPRESA_ID_EMPRESA")
        REFERENCES "TEXTOS_EVALUACION"("CODIGO_EXCEL", "EMPRESA_ID_EMPRESA")
);

CREATE TABLE IF NOT EXISTS "RESULTADO_CONSOLIDADO" (
    "ID_RESULTADO_CONSOLIDADO" SERIAL PRIMARY KEY,
    "PUNTAJE_AUTOEV" INT NOT NULL,
    "PUNTAJE_JEFE" INT NOT NULL,
    "DIFERENCIA" INT NOT NULL,
    "PERIODO" INT NOT NULL,
    "TRABAJADOR_ID_TRABAJADOR" INT NOT NULL REFERENCES "TRABAJADOR"("ID_TRABAJADOR"),
    "AUTOEVALUACION_ID_AUTOEVALUACION" INT NOT NULL REFERENCES "AUTOEVALUACION"("ID_AUTOEVALUACION"),
    "EVALUACION_JEFATURA_ID_EVALUACION_JEFATURA" INT NULL REFERENCES "EVALUACION_JEFATURA"("ID_EVALUACION_JEFATURA"),
    "TEXTOS_EVALUACION_CODIGO_EXCEL" VARCHAR(10) NOT NULL,
    "TEXTOS_EVALUACION_EMPRESA_ID_EMPRESA" INT NOT NULL,
    UNIQUE ("TRABAJADOR_ID_TRABAJADOR", "TEXTOS_EVALUACION_CODIGO_EXCEL", "PERIODO"),
    FOREIGN KEY ("TEXTOS_EVALUACION_CODIGO_EXCEL", "TEXTOS_EVALUACION_EMPRESA_ID_EMPRESA")
        REFERENCES "TEXTOS_EVALUACION"("CODIGO_EXCEL", "EMPRESA_ID_EMPRESA")
);
"""


class Command(BaseCommand):
    help = 'Crea las tablas del sistema en PostgreSQL si no existen (seguro para re-deployar)'

    def handle(self, *args, **kwargs):
        self.stdout.write('🔧 Creando tablas del sistema...')
        try:
            with connection.cursor() as cursor:
                cursor.execute(SQL)
            self.stdout.write(self.style.SUCCESS('✅ Tablas creadas/verificadas correctamente.'))
        except Exception as e:
            self.stdout.write(self.style.ERROR(f'❌ Error al crear tablas: {e}'))
            raise